//! HyperAgent library crate - exposes modules for integration tests.
//! Re-exports the same modules as src/main.rs so `tests/` can use them.

#![allow(dead_code)]

pub mod agent;
pub mod agent_graph;
pub mod analytics;
pub mod bench;
pub mod billing;
pub mod cli;
pub mod computer_use_cross;
pub mod config;
pub mod dep_graph;
pub mod diff;
pub mod diff_view;
pub mod error_recovery;
pub mod eval;
pub mod git;
pub mod hooks;
pub mod i18n;
pub mod index;
pub mod kanban;
pub mod keychain;
pub mod knowledge;
pub mod llm;
pub mod llm_cache;
pub mod mcp;
pub mod memory;
pub mod metrics;
pub mod modes;
pub mod onboarding;
pub mod plugin;
pub mod refactor;
pub mod repl;
#[cfg(feature = "tui")]
pub mod repl_tui;
pub mod retrieval;
pub mod router;
pub mod ci_fix;
pub mod analyze;
pub mod swarm;
pub mod skill_market;
pub mod serve;
pub mod sandbox;
pub mod scaffold;
pub mod scaffold_templates;
pub mod security;
pub mod session;
pub mod sync;
pub mod spinner;
pub mod team;
pub mod saas;
pub mod test_gen;
pub mod test_runner;
#[cfg(feature = "tui")]
pub mod tui;
pub mod updater;
pub mod web_search;