#![allow(unused)]
//! Project scaffolding — create new projects from templates
//!
//! Usage: `hyper scaffold <name> --type <rust|python|ts>`

use anyhow::Result;
use std::path::Path;

/// Available project templates
pub enum ProjectType {
    Rust,
    Python,
    TypeScript,
}

impl ProjectType {
    fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "rust" | "rs" => Some(ProjectType::Rust),
            "python" | "py" => Some(ProjectType::Python),
            "typescript" | "ts" | "node" => Some(ProjectType::TypeScript),
            _ => None,
        }
    }
}

/// Scaffold a new project
pub fn scaffold(name: &str, project_type: &str, dir: &Path) -> Result<()> {
    let ptype = ProjectType::from_str(project_type)
        .ok_or_else(|| anyhow::anyhow!("Unknown project type: {project_type}. Use: rust, python, ts"))?;

    let project_dir = dir.join(name);
    if project_dir.exists() {
        anyhow::bail!("Directory already exists: {}", project_dir.display());
    }

    std::fs::create_dir_all(&project_dir)?;

    match ptype {
        ProjectType::Rust => scaffold_rust(name, &project_dir)?,
        ProjectType::Python => scaffold_python(name, &project_dir)?,
        ProjectType::TypeScript => scaffold_typescript(name, &project_dir)?,
    }

    println!("✅ Created project '{}' at {}", name, project_dir.display());
    println!("\nNext steps:");
    println!("  cd {}", name);
    match ptype {
        ProjectType::Rust => println!("  cargo build"),
        ProjectType::Python => println!("  pip install -r requirements.txt"),
        ProjectType::TypeScript => println!("  npm install"),
    }

    Ok(())
}

fn scaffold_rust(name: &str, dir: &Path) -> Result<()> {
    std::fs::write(
        dir.join("Cargo.toml"),
        format!(r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
description = "{name} — generated by HyperAgent"

[dependencies]
anyhow = "1.0"
serde = {{ version = "1.0", features = ["derive"] }}
tokio = {{ version = "1", features = ["full"] }}
"#),
    )?;

    std::fs::create_dir_all(dir.join("src"))?;
    std::fs::write(
        dir.join("src").join("main.rs"),
        "fn main() -> anyhow::Result<()> {\n    println!(\"Hello, world!\");\n    Ok(())\n}\n",
    )?;

    std::fs::write(dir.join(".gitignore"), "target/\n.hyper/\n")?;
    Ok(())
}

fn scaffold_python(name: &str, dir: &Path) -> Result<()> {
    std::fs::write(
        dir.join("README.md"),
        format!("# {name}\n\nGenerated by HyperAgent\n"),
    )?;
    std::fs::write(
        dir.join("requirements.txt"),
        "requests>=2.31\nclick>=8.1\n",
    )?;
    std::fs::write(
        dir.join("main.py"),
        "def main():\n    print(\"Hello, world!\")\n\n\nif __name__ == \"__main__\":\n    main()\n",
    )?;
    std::fs::write(dir.join(".gitignore"), "__pycache__/\n.venv/\n")?;
    Ok(())
}

fn scaffold_typescript(name: &str, dir: &Path) -> Result<()> {
    std::fs::write(
        dir.join("package.json"),
        format!(r#"{{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "build": "tsc",
    "start": "node dist/index.js"
  }},
  "devDependencies": {{
    "typescript": "^5.0"
  }}
}}
"#),
    )?;

    std::fs::write(
        dir.join("tsconfig.json"),
        r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "strict": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": ["src/**/*"]
}
"#,
    )?;

    std::fs::create_dir_all(dir.join("src"))?;
    std::fs::write(
        dir.join("src").join("index.ts"),
        "function main(): void {\n    console.log(\"Hello, world!\");\n}\n\nmain();\n",
    )?;

    std::fs::write(dir.join(".gitignore"), "node_modules/\ndist/\n")?;
    Ok(())
}


#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn temp_dir(suffix: &str) -> PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!("hyperagent_scaffold_{}_{}", std::process::id(), suffix));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn test_project_type_parsing() {
        // The enum is private but we can test via scaffold() entrypoint
        // Just exercise all valid type names
        for name in &["rust", "rs", "RUST", "Rust"] {
            let dir = temp_dir(&format!("rust_{}", name));
            scaffold("proj", name, &dir).unwrap();
            assert!(dir.join("proj").join("Cargo.toml").exists());
            std::fs::remove_dir_all(&dir).ok();
        }
    }

    #[test]
    fn test_project_type_python_aliases() {
        for name in &["python", "py", "Python"] {
            let dir = temp_dir(&format!("py_{}", name));
            scaffold("proj", name, &dir).unwrap();
            assert!(dir.join("proj").join("main.py").exists());
            assert!(dir.join("proj").join("requirements.txt").exists());
            std::fs::remove_dir_all(&dir).ok();
        }
    }

    #[test]
    fn test_project_type_typescript_aliases() {
        for name in &["typescript", "ts", "node", "TypeScript"] {
            let dir = temp_dir(&format!("ts_{}", name));
            scaffold("proj", name, &dir).unwrap();
            assert!(dir.join("proj").join("package.json").exists());
            assert!(dir.join("proj").join("tsconfig.json").exists());
            std::fs::remove_dir_all(&dir).ok();
        }
    }

    #[test]
    fn test_unknown_project_type_errors() {
        let dir = temp_dir("unknown");
        let result = scaffold("proj", "java", &dir);
        assert!(result.is_err());
        let msg = format!("{}", result.unwrap_err());
        assert!(msg.contains("Unknown project type"));
        assert!(msg.contains("java"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn test_existing_directory_errors() {
        let dir = temp_dir("exists");
        std::fs::create_dir_all(dir.join("proj")).unwrap();
        let result = scaffold("proj", "rust", &dir);
        assert!(result.is_err());
        let msg = format!("{}", result.unwrap_err());
        assert!(msg.contains("already exists"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn test_rust_scaffold_creates_files() {
        let dir = temp_dir("rust_files");
        scaffold("myapp", "rust", &dir).unwrap();
        let proj = dir.join("myapp");
        assert!(proj.join("Cargo.toml").exists());
        assert!(proj.join("src").join("main.rs").exists());
        assert!(proj.join(".gitignore").exists());

        // Validate Cargo.toml content
        let cargo = std::fs::read_to_string(proj.join("Cargo.toml")).unwrap();
        assert!(cargo.contains(r#"name = "myapp""#));
        assert!(cargo.contains("anyhow"));

        // Validate gitignore
        let gitignore = std::fs::read_to_string(proj.join(".gitignore")).unwrap();
        assert!(gitignore.contains("target/"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn test_python_scaffold_creates_files() {
        let dir = temp_dir("py_files");
        scaffold("script", "python", &dir).unwrap();
        let proj = dir.join("script");
        assert!(proj.join("README.md").exists());
        assert!(proj.join("requirements.txt").exists());
        assert!(proj.join("main.py").exists());
        assert!(proj.join(".gitignore").exists());

        let reqs = std::fs::read_to_string(proj.join("requirements.txt")).unwrap();
        assert!(reqs.contains("requests"));

        let gitignore = std::fs::read_to_string(proj.join(".gitignore")).unwrap();
        assert!(gitignore.contains("__pycache__"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn test_typescript_scaffold_creates_files() {
        let dir = temp_dir("ts_files");
        scaffold("webapp", "ts", &dir).unwrap();
        let proj = dir.join("webapp");
        assert!(proj.join("package.json").exists());
        assert!(proj.join("tsconfig.json").exists());
        assert!(proj.join("src").join("index.ts").exists());
        assert!(proj.join(".gitignore").exists());

        let pkg = std::fs::read_to_string(proj.join("package.json")).unwrap();
        assert!(pkg.contains(r#""name": "webapp""#));
        assert!(pkg.contains("typescript"));

        let tsconfig = std::fs::read_to_string(proj.join("tsconfig.json")).unwrap();
        assert!(tsconfig.contains("strict"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn test_rust_main_rs_compiles() {
        // Verify the generated main.rs is syntactically valid Rust
        let dir = temp_dir("rust_compile");
        scaffold("app", "rust", &dir).unwrap();
        let main_rs = std::fs::read_to_string(dir.join("app/src/main.rs")).unwrap();
        assert!(main_rs.contains("fn main()"));
        assert!(main_rs.contains("anyhow::Result"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn test_empty_string_project_type_errors() {
        let dir = temp_dir("empty_type");
        let result = scaffold("proj", "", &dir);
        assert!(result.is_err());
        std::fs::remove_dir_all(&dir).ok();
    }
}
