//! Project scaffolding — create new projects from templates
//!
//! Usage: `hyper scaffold <name> --type <rust|python|ts>`

use anyhow::Result;
use std::path::Path;

/// Available project templates
pub enum ProjectType {
    Rust,
    Python,
    TypeScript,
}

impl ProjectType {
    fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "rust" | "rs" => Some(ProjectType::Rust),
            "python" | "py" => Some(ProjectType::Python),
            "typescript" | "ts" | "node" => Some(ProjectType::TypeScript),
            _ => None,
        }
    }
}

/// Scaffold a new project
pub fn scaffold(name: &str, project_type: &str, dir: &Path) -> Result<()> {
    let ptype = ProjectType::from_str(project_type)
        .ok_or_else(|| anyhow::anyhow!("Unknown project type: {project_type}. Use: rust, python, ts"))?;

    let project_dir = dir.join(name);
    if project_dir.exists() {
        anyhow::bail!("Directory already exists: {}", project_dir.display());
    }

    std::fs::create_dir_all(&project_dir)?;

    match ptype {
        ProjectType::Rust => scaffold_rust(name, &project_dir)?,
        ProjectType::Python => scaffold_python(name, &project_dir)?,
        ProjectType::TypeScript => scaffold_typescript(name, &project_dir)?,
    }

    println!("✅ Created project '{}' at {}", name, project_dir.display());
    println!("\nNext steps:");
    println!("  cd {}", name);
    match ptype {
        ProjectType::Rust => println!("  cargo build"),
        ProjectType::Python => println!("  pip install -r requirements.txt"),
        ProjectType::TypeScript => println!("  npm install"),
    }

    Ok(())
}

fn scaffold_rust(name: &str, dir: &Path) -> Result<()> {
    std::fs::write(
        dir.join("Cargo.toml"),
        format!(r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
description = "{name} — generated by HyperAgent"

[dependencies]
anyhow = "1.0"
serde = {{ version = "1.0", features = ["derive"] }}
tokio = {{ version = "1", features = ["full"] }}
"#),
    )?;

    std::fs::create_dir_all(dir.join("src"))?;
    std::fs::write(
        dir.join("src").join("main.rs"),
        "fn main() -> anyhow::Result<()> {\n    println!(\"Hello, world!\");\n    Ok(())\n}\n",
    )?;

    std::fs::write(dir.join(".gitignore"), "target/\n.hyper/\n")?;
    Ok(())
}

fn scaffold_python(name: &str, dir: &Path) -> Result<()> {
    std::fs::write(
        dir.join("README.md"),
        format!("# {name}\n\nGenerated by HyperAgent\n"),
    )?;
    std::fs::write(
        dir.join("requirements.txt"),
        "requests>=2.31\nclick>=8.1\n",
    )?;
    std::fs::write(
        dir.join("main.py"),
        "def main():\n    print(\"Hello, world!\")\n\n\nif __name__ == \"__main__\":\n    main()\n",
    )?;
    std::fs::write(dir.join(".gitignore"), "__pycache__/\n.venv/\n")?;
    Ok(())
}

fn scaffold_typescript(name: &str, dir: &Path) -> Result<()> {
    std::fs::write(
        dir.join("package.json"),
        format!(r#"{{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "build": "tsc",
    "start": "node dist/index.js"
  }},
  "devDependencies": {{
    "typescript": "^5.0"
  }}
}}
"#),
    )?;

    std::fs::write(
        dir.join("tsconfig.json"),
        r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "strict": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": ["src/**/*"]
}
"#,
    )?;

    std::fs::create_dir_all(dir.join("src"))?;
    std::fs::write(
        dir.join("src").join("index.ts"),
        "function main(): void {\n    console.log(\"Hello, world!\");\n}\n\nmain();\n",
    )?;

    std::fs::write(dir.join(".gitignore"), "node_modules/\ndist/\n")?;
    Ok(())
}
