const t:Record<string,Record<string,string>>={
en:{signIn:'Sign In',register:'Register',email:'Email',password:'Password',logout:'Sign Out',orgs:'Organizations',newOrg:'+ New Org',newAgent:'+ Agent',assignTask:'Assign Task',settings:'Settings',provider:'Provider',model:'Model',apiKey:'API Key',temperature:'Temperature',save:'Save',cancel:'Cancel',total:'Total',done:'Done',rate:'Rate',liveEvents:'Live Events',waiting:'Waiting...',noAgents:'No agents yet',selectOrg:'Select an organization',name:'Name',description:'Description',role:'Role',create:'Create',taskDesc:'Describe task...',dashboard:'Agent Platform'},
'zh-CN':{signIn:'登录',register:'注册',email:'邮箱',password:'密码',logout:'退出',orgs:'组织',newOrg:'+ 新建',newAgent:'+ Agent',assignTask:'分配任务',settings:'设置',provider:'服务商',model:'模型',apiKey:'密钥',temperature:'温度',save:'保存',cancel:'取消',total:'总计',done:'完成',rate:'成功率',liveEvents:'实时事件',waiting:'等待中...',noAgents:'暂无Agent',selectOrg:'选择组织',name:'名称',description:'描述',role:'角色',create:'创建',taskDesc:'描述任务...',dashboard:'Agent 平台'},
es:{signIn:'Iniciar',register:'Registrar',email:'Correo',password:'Contraseña',logout:'Salir',orgs:'Org',newOrg:'+ Nueva',newAgent:'+ Agente',assignTask:'Asignar',settings:'Config',provider:'Proveedor',model:'Modelo',apiKey:'Clave',temperature:'Temp',save:'Guardar',cancel:'Cancelar',total:'Total',done:'Hecho',rate:'Tasa',liveEvents:'Eventos',waiting:'Esperando...',noAgents:'Sin agentes',selectOrg:'Seleccionar org',name:'Nombre',description:'Descripción',role:'Rol',create:'Crear',taskDesc:'Describir...',dashboard:'Plataforma'},
ja:{signIn:'ログイン',register:'登録',email:'メール',password:'パスワード',logout:'ログアウト',orgs:'組織',newOrg:'+ 新規',newAgent:'+ Agent',assignTask:'割当',settings:'設定',provider:'提供元',model:'モデル',apiKey:'キー',temperature:'温度',save:'保存',cancel:'取消',total:'合計',done:'完了',rate:'率',liveEvents:'イベント',waiting:'待機中',noAgents:'なし',selectOrg:'組織選択',name:'名前',description:'説明',role:'役割',create:'作成',taskDesc:'説明...',dashboard:'プラットフォーム'},
ko:{signIn:'로그인',register:'가입',email:'이메일',password:'비밀번호',logout:'로그아웃',orgs:'조직',newOrg:'+ 새로',newAgent:'+ 에이전트',assignTask:'할당',settings:'설정',provider:'제공자',model:'모델',apiKey:'키',temperature:'온도',save:'저장',cancel:'취소',total:'전체',done:'완료',rate:'성공률',liveEvents:'이벤트',waiting:'대기 중',noAgents:'없음',selectOrg:'조직 선택',name:'이름',description:'설명',role:'역할',create:'생성',taskDesc:'설명...',dashboard:'플랫폼'},
fr:{signIn:'Connexion',register:'Inscription',email:'Email',password:'Mot de passe',logout:'Déconnexion',orgs:'Organisations',newOrg:'+ Nouvelle',newAgent:'+ Agent',assignTask:'Assigner',settings:'Paramètres',provider:'Fournisseur',model:'Modèle',apiKey:'Clé',temperature:'Temp',save:'Sauver',cancel:'Annuler',total:'Total',done:'Fait',rate:'Taux',liveEvents:'Événements',waiting:'Attente...',noAgents:'Aucun',selectOrg:'Sélectionner',name:'Nom',description:'Description',role:'Rôle',create:'Créer',taskDesc:'Décrire...',dashboard:'Plateforme'},
de:{signIn:'Anmelden',register:'Registrieren',email:'E-Mail',password:'Passwort',logout:'Abmelden',orgs:'Org',newOrg:'+ Neu',newAgent:'+ Agent',assignTask:'Aufgabe',settings:'Einstellungen',provider:'Anbieter',model:'Modell',apiKey:'API-Schlüssel',temperature:'Temp',save:'Speichern',cancel:'Abbrechen',total:'Gesamt',done:'Erledigt',rate:'Quote',liveEvents:'Ereignisse',waiting:'Warten...',noAgents:'Keine',selectOrg:'Org wählen',name:'Name',description:'Beschreibung',role:'Rolle',create:'Erstellen',taskDesc:'Beschreiben...',dashboard:'Plattform'},
ru:{signIn:'Вход',register:'Регистрация',email:'Почта',password:'Пароль',logout:'Выход',orgs:'Орг',newOrg:'+ Новая',newAgent:'+ Агент',assignTask:'Задача',settings:'Настройки',provider:'Провайдер',model:'Модель',apiKey:'Ключ',temperature:'Темп',save:'Сохранить',cancel:'Отмена',total:'Всего',done:'Готово',rate:'Успех',liveEvents:'События',waiting:'Ожидание...',noAgents:'Нет',selectOrg:'Выбрать',name:'Имя',description:'Описание',role:'Роль',create:'Создать',taskDesc:'Описать...',dashboard:'Платформа'},
pt:{signIn:'Entrar',register:'Registrar',email:'Email',password:'Senha',logout:'Sair',orgs:'Org',newOrg:'+ Nova',newAgent:'+ Agente',assignTask:'Atribuir',settings:'Config',provider:'Provedor',model:'Modelo',apiKey:'Chave',temperature:'Temp',save:'Salvar',cancel:'Cancelar',total:'Total',done:'Feito',rate:'Taxa',liveEvents:'Eventos',waiting:'Aguardando...',noAgents:'Nenhum',selectOrg:'Selecionar',name:'Nome',description:'Descrição',role:'Função',create:'Criar',taskDesc:'Descrever...',dashboard:'Plataforma'},
}
const ln:Record<string,string>={en:'English','zh-CN':'中文',es:'Español',fr:'Français',ja:'日本語',ko:'한국어',de:'Deutsch',ru:'Русский',pt:'Português'}
let cl=localStorage.getItem('lang')||'en';if(cl==='zh')cl='zh-CN';if(!t[cl])cl='en'
export function tt(k:string):string{return t[cl]?.[k]||t['en']?.[k]||k}
export function sl(l:string){localStorage.setItem('lang',l);window.location.reload()}
export function gl(){return cl}
export function al(){return Object.keys(ln).map(k=>({code:k,name:ln[k]}))}
