// 20-language i18n for Agent Platform
const t:Record<string,Record<string,string>>={
en:{signIn:'Sign In',register:'Register',email:'Email',password:'Password',logout:'Sign Out',orgs:'Organizations',newOrg:'+ New Org',newAgent:'+ Agent',assignTask:'Assign Task',settings:'Settings',provider:'Provider',model:'Model',apiKey:'API Key',temperature:'Temperature',save:'Save',cancel:'Cancel',total:'Total',done:'Done',rate:'Rate',liveEvents:'Live Events',waiting:'Waiting...',noAgents:'No agents',selectOrg:'Select organization',name:'Name',description:'Description',role:'Role',create:'Create',taskDesc:'Describe task...',dashboard:'Agent Platform'},
'zh-CN':{signIn:'登录',register:'注册',email:'邮箱',password:'密码',logout:'退出',orgs:'组织',newOrg:'+ 新建',newAgent:'+ Agent',assignTask:'分配任务',settings:'设置',provider:'服务商',model:'模型',apiKey:'密钥',temperature:'温度',save:'保存',cancel:'取消',total:'总计',done:'完成',rate:'成功率',liveEvents:'实时事件',waiting:'等待中...',noAgents:'暂无Agent',selectOrg:'选择组织',name:'名称',description:'描述',role:'角色',create:'创建',taskDesc:'描述任务...',dashboard:'Agent平台'},
es:{signIn:'Iniciar',register:'Registrar',email:'Correo',password:'Contraseña',logout:'Salir',orgs:'Org',newOrg:'+ Nueva',newAgent:'+ Agente',assignTask:'Asignar',settings:'Config',provider:'Proveedor',model:'Modelo',apiKey:'Clave',temperature:'Temp',save:'Guardar',cancel:'Cancelar',total:'Total',done:'Hecho',rate:'Tasa',liveEvents:'Eventos',waiting:'Esperando...',noAgents:'Sin agentes',selectOrg:'Seleccionar',name:'Nombre',description:'Descripción',role:'Rol',create:'Crear',taskDesc:'Describir...',dashboard:'Plataforma'},
fr:{signIn:'Connexion',register:'Inscription',email:'Email',password:'Mot de passe',logout:'Déconnexion',orgs:'Org',newOrg:'+ Nouvelle',newAgent:'+ Agent',assignTask:'Assigner',settings:'Paramètres',provider:'Fournisseur',model:'Modèle',apiKey:'Clé',temperature:'Temp',save:'Sauver',cancel:'Annuler',total:'Total',done:'Fait',rate:'Taux',liveEvents:'Événements',waiting:'Attente...',noAgents:'Aucun',selectOrg:'Sélectionner',name:'Nom',description:'Description',role:'Rôle',create:'Créer',taskDesc:'Décrire...',dashboard:'Plateforme'},
ja:{signIn:'ログイン',register:'登録',email:'メール',password:'パスワード',logout:'ログアウト',orgs:'組織',newOrg:'+ 新規',newAgent:'+ Agent',assignTask:'割当',settings:'設定',provider:'提供元',model:'モデル',apiKey:'キー',temperature:'温度',save:'保存',cancel:'取消',total:'合計',done:'完了',rate:'率',liveEvents:'イベント',waiting:'待機中',noAgents:'なし',selectOrg:'組織選択',name:'名前',description:'説明',role:'役割',create:'作成',taskDesc:'説明...',dashboard:'プラットフォーム'},
ko:{signIn:'로그인',register:'가입',email:'이메일',password:'비밀번호',logout:'로그아웃',orgs:'조직',newOrg:'+ 새로',newAgent:'+ 에이전트',assignTask:'할당',settings:'설정',provider:'제공자',model:'모델',apiKey:'키',temperature:'온도',save:'저장',cancel:'취소',total:'전체',done:'완료',rate:'성공률',liveEvents:'이벤트',waiting:'대기 중',noAgents:'없음',selectOrg:'선택',name:'이름',description:'설명',role:'역할',create:'생성',taskDesc:'설명...',dashboard:'플랫폼'},
de:{signIn:'Anmelden',register:'Registrieren',email:'E-Mail',password:'Passwort',logout:'Abmelden',orgs:'Org',newOrg:'+ Neu',newAgent:'+ Agent',assignTask:'Aufgabe',settings:'Einstellungen',provider:'Anbieter',model:'Modell',apiKey:'API-Schlüssel',temperature:'Temp',save:'Speichern',cancel:'Abbrechen',total:'Gesamt',done:'Erledigt',rate:'Quote',liveEvents:'Ereignisse',waiting:'Warten...',noAgents:'Keine',selectOrg:'Wählen',name:'Name',description:'Beschreibung',role:'Rolle',create:'Erstellen',taskDesc:'Beschreiben...',dashboard:'Plattform'},
ru:{signIn:'Вход',register:'Регистрация',email:'Почта',password:'Пароль',logout:'Выход',orgs:'Орг',newOrg:'+ Новая',newAgent:'+ Агент',assignTask:'Задача',settings:'Настройки',provider:'Провайдер',model:'Модель',apiKey:'Ключ',temperature:'Темп',save:'Сохранить',cancel:'Отмена',total:'Всего',done:'Готово',rate:'Успех',liveEvents:'События',waiting:'Ожидание...',noAgents:'Нет',selectOrg:'Выбрать',name:'Имя',description:'Описание',role:'Роль',create:'Создать',taskDesc:'Описать...',dashboard:'Платформа'},
pt:{signIn:'Entrar',register:'Registrar',email:'Email',password:'Senha',logout:'Sair',orgs:'Org',newOrg:'+ Nova',newAgent:'+ Agente',assignTask:'Atribuir',settings:'Config',provider:'Provedor',model:'Modelo',apiKey:'Chave',temperature:'Temp',save:'Salvar',cancel:'Cancelar',total:'Total',done:'Feito',rate:'Taxa',liveEvents:'Eventos',waiting:'Aguardando...',noAgents:'Nenhum',selectOrg:'Selecionar',name:'Nome',description:'Descrição',role:'Função',create:'Criar',taskDesc:'Descrever...',dashboard:'Plataforma'},
vi:{signIn:'Đăng nhập',register:'Đăng ký',email:'Email',password:'Mật khẩu',logout:'Thoát',orgs:'Tổ chức',newOrg:'+ Mới',newAgent:'+ Agent',assignTask:'Giao việc',settings:'Cài đặt',provider:'Nhà cung cấp',model:'Mô hình',apiKey:'Khóa API',temperature:'Nhiệt độ',save:'Lưu',cancel:'Hủy',total:'Tổng',done:'Xong',rate:'Tỷ lệ',liveEvents:'Sự kiện',waiting:'Đợi...',noAgents:'Không có',selectOrg:'Chọn tổ chức',name:'Tên',description:'Mô tả',role:'Vai trò',create:'Tạo',taskDesc:'Mô tả...',dashboard:'Nền tảng'},
it:{signIn:'Accedi',register:'Registrati',email:'Email',password:'Password',logout:'Esci',orgs:'Org',newOrg:'+ Nuova',newAgent:'+ Agente',assignTask:'Assegna',settings:'Impostazioni',provider:'Provider',model:'Modello',apiKey:'Chiave',temperature:'Temp',save:'Salva',cancel:'Annulla',total:'Totale',done:'Fatto',rate:'Tasso',liveEvents:'Eventi',waiting:'Attesa...',noAgents:'Nessuno',selectOrg:'Seleziona',name:'Nome',description:'Descrizione',role:'Ruolo',create:'Crea',taskDesc:'Descrivi...',dashboard:'Piattaforma'},
tr:{signIn:'Giriş',register:'Kayıt',email:'E-posta',password:'Şifre',logout:'Çıkış',orgs:'Kuruluş',newOrg:'+ Yeni',newAgent:'+ Ajan',assignTask:'Görev Ver',settings:'Ayarlar',provider:'Sağlayıcı',model:'Model',apiKey:'API Anahtarı',temperature:'Sıcaklık',save:'Kaydet',cancel:'İptal',total:'Toplam',done:'Tamam',rate:'Oran',liveEvents:'Olaylar',waiting:'Bekleniyor...',noAgents:'Ajan yok',selectOrg:'Kuruluş seç',name:'Ad',description:'Açıklama',role:'Rol',create:'Oluştur',taskDesc:'Görev...',dashboard:'Platform'},
pl:{signIn:'Zaloguj',register:'Rejestracja',email:'Email',password:'Hasło',logout:'Wyloguj',orgs:'Org',newOrg:'+ Nowa',newAgent:'+ Agent',assignTask:'Przydziel',settings:'Ustawienia',provider:'Dostawca',model:'Model',apiKey:'Klucz API',temperature:'Temp',save:'Zapisz',cancel:'Anuluj',total:'Razem',done:'Gotowe',rate:'Wskaźnik',liveEvents:'Zdarzenia',waiting:'Czekam...',noAgents:'Brak',selectOrg:'Wybierz',name:'Nazwa',description:'Opis',role:'Rola',create:'Utwórz',taskDesc:'Opisz...',dashboard:'Platforma'},
ar:{signIn:'تسجيل',register:'حساب جديد',email:'البريد',password:'كلمة المرور',logout:'خروج',orgs:'منظمات',newOrg:'+ جديدة',newAgent:'+ وكيل',assignTask:'مهمة',settings:'إعدادات',provider:'مزود',model:'نموذج',apiKey:'مفتاح',temperature:'حرارة',save:'حفظ',cancel:'إلغاء',total:'المجموع',done:'تم',rate:'نسبة',liveEvents:'أحداث',waiting:'انتظار...',noAgents:'لا وكلاء',selectOrg:'اختر',name:'اسم',description:'وصف',role:'دور',create:'إنشاء',taskDesc:'وصف...',dashboard:'منصة'},
id:{signIn:'Masuk',register:'Daftar',email:'Email',password:'Sandi',logout:'Keluar',orgs:'Organisasi',newOrg:'+ Baru',newAgent:'+ Agen',assignTask:'Tugaskan',settings:'Pengaturan',provider:'Penyedia',model:'Model',apiKey:'Kunci API',temperature:'Suhu',save:'Simpan',cancel:'Batal',total:'Total',done:'Selesai',rate:'Tingkat',liveEvents:'Peristiwa',waiting:'Menunggu...',noAgents:'Tidak ada',selectOrg:'Pilih org',name:'Nama',description:'Deskripsi',role:'Peran',create:'Buat',taskDesc:'Deskripsikan...',dashboard:'Platform'},
uk:{signIn:'Вхід',register:'Реєстрація',email:'Пошта',password:'Пароль',logout:'Вихід',orgs:'Орг',newOrg:'+ Нова',newAgent:'+ Агент',assignTask:'Завдання',settings:'Налаштування',provider:'Провайдер',model:'Модель',apiKey:'Ключ',temperature:'Темп',save:'Зберегти',cancel:'Скасувати',total:'Всього',done:'Готово',rate:'Успіх',liveEvents:'Події',waiting:'Очікування...',noAgents:'Немає',selectOrg:'Вибрати',name:'Назва',description:'Опис',role:'Роль',create:'Створити',taskDesc:'Описати...',dashboard:'Платформа'},
nl:{signIn:'Inloggen',register:'Registreren',email:'E-mail',password:'Wachtwoord',logout:'Uitloggen',orgs:'Org',newOrg:'+ Nieuw',newAgent:'+ Agent',assignTask:'Toewijzen',settings:'Instellingen',provider:'Provider',model:'Model',apiKey:'API-sleutel',temperature:'Temp',save:'Opslaan',cancel:'Annuleren',total:'Totaal',done:'Klaar',rate:'Percentage',liveEvents:'Gebeurtenissen',waiting:'Wachten...',noAgents:'Geen',selectOrg:'Selecteren',name:'Naam',description:'Beschrijving',role:'Rol',create:'Maken',taskDesc:'Beschrijven...',dashboard:'Platform'},
th:{signIn:'เข้าสู่ระบบ',register:'ลงทะเบียน',email:'อีเมล',password:'รหัสผ่าน',logout:'ออก',orgs:'องค์กร',newOrg:'+ ใหม่',newAgent:'+ ตัวแทน',assignTask:'มอบหมาย',settings:'ตั้งค่า',provider:'ผู้ให้บริการ',model:'โมเดล',apiKey:'คีย์',temperature:'อุณหภูมิ',save:'บันทึก',cancel:'ยกเลิก',total:'รวม',done:'เสร็จ',rate:'อัตรา',liveEvents:'เหตุการณ์',waiting:'รอ...',noAgents:'ไม่มี',selectOrg:'เลือกองค์กร',name:'ชื่อ',description:'คำอธิบาย',role:'บทบาท',create:'สร้าง',taskDesc:'อธิบาย...',dashboard:'แพลตฟอร์ม'},
bn:{signIn:'প্রবেশ',register:'নিবন্ধন',email:'ইমেইল',password:'পাসওয়ার্ড',logout:'প্রস্থান',orgs:'সংস্থা',newOrg:'+ নতুন',newAgent:'+ এজেন্ট',assignTask:'দায়িত্ব',settings:'সেটিংস',provider:'প্রদানকারী',model:'মডেল',apiKey:'API কী',temperature:'তাপমাত্রা',save:'সংরক্ষণ',cancel:'বাতিল',total:'মোট',done:'সম্পন্ন',rate:'হার',liveEvents:'ইভেন্ট',waiting:'অপেক্ষা...',noAgents:'নেই',selectOrg:'নির্বাচন',name:'নাম',description:'বিবরণ',role:'ভূমিকা',create:'তৈরি',taskDesc:'বর্ণনা...',dashboard:'প্লাটফর্ম'},
hi:{signIn:'लॉगिन',register:'रजिस्टर',email:'ईमेल',password:'पासवर्ड',logout:'लॉगआउट',orgs:'संगठन',newOrg:'+ नया',newAgent:'+ एजेंट',assignTask:'कार्य',settings:'सेटिंग्स',provider:'प्रदाता',model:'मॉडल',apiKey:'API कुंजी',temperature:'तापमान',save:'सहेजें',cancel:'रद्द',total:'कुल',done:'पूर्ण',rate:'दर',liveEvents:'घटनाएं',waiting:'प्रतीक्षा...',noAgents:'कोई नहीं',selectOrg:'चुनें',name:'नाम',description:'विवरण',role:'भूमिका',create:'बनाएं',taskDesc:'वर्णन...',dashboard:'प्लेटफ़ॉर्म'},
}
const ln:Record<string,string>={en:'English','zh-CN':'中文',es:'Español',fr:'Français',ja:'日本語',ko:'한국어',de:'Deutsch',ru:'Русский',pt:'Português',vi:'Tiếng Việt',it:'Italiano',tr:'Türkçe',pl:'Polski',ar:'العربية',id:'Indonesia',uk:'Українська',nl:'Nederlands',th:'ไทย',bn:'বাংলা',hi:'हिन्दी'}
let cl=localStorage.getItem('lang')||'en';if(cl==='zh')cl='zh-CN';if(!t[cl])cl='en'
export function tt(k:string):string{return t[cl]?.[k]||t['en']?.[k]||k}
export function sl(l:string){localStorage.setItem('lang',l);window.location.reload()}
export function gl(){return cl}
export function al(){return Object.keys(ln).map(k=>({code:k,name:ln[k]}))}
