import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function SettingsPage({ onSave, onClose, current }) {
    const [provider, setProvider] = useState(current.provider);
    const [model, setModel] = useState(current.model);
    const [apiKey, setApiKey] = useState(current.api_key);
    const [temp, setTemp] = useState(current.temperature);
    return (_jsxs("div", { className: "p-6 max-w-md mx-auto", children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "Model Settings" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs text-gray-500 mb-1", children: "Provider" }), _jsx("select", { value: provider, onChange: e => setProvider(e.target.value), className: "w-full px-3 py-2 rounded-lg bg-[#06060a] border border-gray-800 text-sm", children: ['openai', 'anthropic', 'deepseek', 'groq', 'together', 'local'].map(p => _jsx("option", { value: p, children: p }, p)) })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs text-gray-500 mb-1", children: "Model" }), _jsx("input", { value: model, onChange: e => setModel(e.target.value), className: "w-full px-3 py-2 rounded-lg bg-[#06060a] border border-gray-800 text-sm", placeholder: "gpt-4o" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs text-gray-500 mb-1", children: "API Key" }), _jsx("input", { value: apiKey, onChange: e => setApiKey(e.target.value), type: "password", className: "w-full px-3 py-2 rounded-lg bg-[#06060a] border border-gray-800 text-sm", placeholder: "sk-..." })] }), _jsxs("div", { children: [_jsxs("label", { className: "block text-xs text-gray-500 mb-1", children: ["Temperature: ", temp.toFixed(1)] }), _jsx("input", { type: "range", min: "0", max: "2", step: "0.1", value: temp, onChange: e => setTemp(parseFloat(e.target.value)), className: "w-full accent-indigo-500" })] }), _jsxs("div", { className: "flex gap-2 pt-2", children: [_jsx("button", { onClick: () => onSave({ provider, model, api_key: apiKey, temperature: temp }), className: "flex-1 py-2 bg-indigo-600 hover:bg-indigo-500 rounded-lg text-sm", children: "Save" }), _jsx("button", { onClick: onClose, className: "flex-1 py-2 bg-gray-800 hover:bg-gray-700 rounded-lg text-sm", children: "Cancel" })] })] })] }));
}
